[package]
name = "mariadb-mysql-cdc"
version = "0.1.0"
edition = "2024"

[features]
default = []
integration-failpoints = []

[dependencies]
mysql = { version = "28.0.0", features = ["native-tls"] }
mysqlclient-sys = "0.5.2"
native-tls = "0.2.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.10.9"
mysql_cdc = { path = "vendor/mysql_cdc" }
